using System.Text.Json;
using TiaProjectExporter.Application;
using TiaProjectExporter.Application.Abstractions;
using TiaProjectExporter.Core.Models;
using TiaProjectExporter.Export.Repository;
using TiaProjectExporter.Infrastructure.Serialization;

namespace TiaProjectExporter.Export.Stages;

/// <summary>
/// Creates the export repository skeleton and initial AI-oriented metadata files.
/// </summary>
public sealed class RepositoryLayoutStage : IExportStage
{
    /// <inheritdoc />
    public string Name => "Repository Layout";

    /// <inheritdoc />
    public async Task ExecuteAsync(ExportExecutionContext context, CancellationToken cancellationToken)
    {
        foreach (var directory in ExportRepositoryLayout.Directories)
        {
            await context.EnsureDirectoryAsync(directory, cancellationToken).ConfigureAwait(false);
        }

        var generatedAt = DateTimeOffset.UtcNow;
        var jsonOptions = JsonOptionsFactory.CreateDefault();

        var readme = """
            # TIA Project Export

            This repository contains a structured export generated by TIA Project Exporter.

            Generated content is organized for:

            - Git version control
            - VS Code navigation
            - AI-assisted analysis
            - Human-readable review
            """;

        var overview = """
            # Project Overview

            This file will contain a project-level AI summary once real project extraction is connected.
            """;

        var report = """
            # Export Report

            Milestone 1 generated the repository structure successfully.
            """;

        var statistics = JsonSerializer.Serialize(
            new
            {
                GeneratedAt = generatedAt,
                Directories = ExportRepositoryLayout.Directories.Count,
                ExportedObjects = 0
            },
            jsonOptions);

        await WriteIfEnabledAsync(context, "Export/README.md", ExportFormat.Markdown, readme, cancellationToken).ConfigureAwait(false);
        await WriteIfEnabledAsync(context, "Export/PROJECT_OVERVIEW.md", ExportFormat.Markdown, overview, cancellationToken).ConfigureAwait(false);
        await WriteIfEnabledAsync(context, "Export/EXPORT_REPORT.md", ExportFormat.Markdown, report, cancellationToken).ConfigureAwait(false);
        await WriteIfEnabledAsync(context, "Export/PROJECT_STATISTICS.json", ExportFormat.Json, statistics, cancellationToken).ConfigureAwait(false);

        context.AddResult(new ExportedObjectResult("Repository", "InitialLayout", ExportObjectStatus.Succeeded));
        await context.ReportProgressAsync(new ExportProgressUpdate(Name, "Repository skeleton created", 1, 1, TimeSpan.Zero)).ConfigureAwait(false);
    }

    private static Task WriteIfEnabledAsync(
        ExportExecutionContext context,
        string relativePath,
        ExportFormat format,
        string content,
        CancellationToken cancellationToken)
    {
        if (!context.Options.Formats.Contains(format) && format != ExportFormat.Markdown)
        {
            return Task.CompletedTask;
        }

        if (format == ExportFormat.Markdown && !context.Options.GenerateMarkdownSummaries)
        {
            return Task.CompletedTask;
        }

        return context.WriteArtifactAsync(new ExportArtifact(relativePath, format, content), cancellationToken);
    }
}
